git:
  pagers:
    - colorArg: always
      pager: delta --diff-so-fancy --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
os:
  editPreset: nvim
gui:
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  authorColors:
    "*": "#f3be7c"
  theme:
    activeBorderColor:
      - "#b4d4cf"
      - "bold"
    inactiveBorderColor:
      - "#333738"
    optionsTextColor:
      - "#606079"
    selectedLineBgColor:
      - "#252530"
    cherryPickedCommitFgColor:
      - "#d8647e"
    cherryPickedCommitBgColor:
      - "bg"
    markedBaseCommitFgColor:
      - "#f3be7c"
    markedBaseCommitBgColor:
      - "bg"
    unstagedChangesColor:
      - "#d8647e"
    defaultFgColor:
      - "#cdcdcd"
